### ISSUE TITLE
Alexa is timing out very often

### ISSUE THREAD

**Issue by kxkayser** [hardillb/node-red-alexa-home-skill-web#131] opened 2021-12-17 03:08 UTC
Hi. Have been using this great service for almost 2 years and have about 15 devices defined. Lately, in the last month or so, Alexa has been responding with “(device name) not responding.  Please check it’s network connection and power supply” quite often. In fact, most times the first command for a given device she times out but subsequent commands to the same device work normally. Actually, the command works despite the bad return message. My network is very reliable and fast and as I say, this is a relatively new issue. Any ideas about how to debug?  Thanks

**Comment by Bra1nK** [comment] 2021-12-17 06:51
This has been happening here on and off for years and I'm guessing it's an Amazon issue, I think their servers are getting busy especially at peak times.

**Comment by kxkayser** [comment] 2021-12-17 13:39
OK Brian.  Thanks for the quick response.  Let’s see what happens after the holiday shopping is over.

 

Regards,

 

Ken Kayser

Tobaccoville, NC

 

***@***.***

**Comment by Bra1nK** [comment] 2021-12-17 14:09
I think it's more to do with the new Alexa devices coming on line, there's been loads of special offers recently and it's liable to get worse over Xmas at least until they up the capacity. All this assumes my guess is correct.

**Comment by kxkayser** [comment] 2021-12-17 16:05
One additional piece of information. It only happens on devices using your
node. Devices using smartlfe for example work normally

**Comment by SpeedyRS2** [comment] 2021-12-26 16:22
Since a few months I have the problem also more and more often. Meanwhile with almost every call. The action is carried out in the end, but the message still comes. The execution is often also very delayed.

**Comment by kxkayser** [comment] 2021-12-26 16:27
Frankly, it became unusable.  I have switched out all my nodes to with virtual-smart-home.  It required some reprogramming but all responses are now instantaneous.  

 

Ken Kayser

Tobaccoville, NC

 

***@***.***

**Comment by hardillb** [comment] 2021-12-26 16:35
I will try and find some time this week to move the broker and db to a bigger machine. I just haven't had the spare time yet

**Comment by kxkayser** [comment] 2021-12-26 16:39
OK, please let us know when you accomplish this.  I’d like to be able to use it again.

 

Regards,

 

Ken Kayser

Tobaccoville, NC

 

***@***.***

**Comment by hardillb** [comment] 2021-12-27 10:40
New broker/database machine is up and running please let me know how it's going as I don't have access to my test hardware at the moment.

**Comment by Bra1nK** [comment] 2021-12-27 11:00
Devices have stopped responding

**Comment by hardillb** [comment] 2021-12-27 11:13
The broker keeps crashing at the moment, it runs for a long a while then falls over

**Comment by hardillb** [comment] 2021-12-27 11:58
OK, back on old hardware, should be back up (if a little laggy). Will work out what was killing the broker on the new hardware later.

**Comment by Bra1nK** [comment] 2021-12-27 12:53
Yes working again

**Comment by GetUpdate** [comment] 2021-12-27 18:50
Still have the "... antwortet nicht überprüfe die Stromversorgung und die Internetverbindung des Geräts"  problem too. 
-> It switches the device after seconds finaly. 

Is there please any check option where the time went to (e.g. you send us a time stamp back?)?  
   


THX Michael

**Comment by hardillb** [comment] 2021-12-27 18:52
It's the broker backend, not something you can fix. I'll have another do at deploying the new backend machine tomorrow

**Comment by hardillb** [comment] 2021-12-28 09:15
New broker/DB back end swapped in again this morning. Things look to be working properly this time. Please test

**Comment by Bra1nK** [comment] 2021-12-28 09:35
Seems to be OK so far and currently responding faster

**Comment by GetUpdate** [comment] 2021-12-28 10:02
Same, much faster response.  Currently GREAT, loving it.

**Comment by SpeedyRS2** [comment] 2021-12-28 10:59
Right at the moment, everything works on warp speed. Really great. Thank you very much :-)

**Comment by loxatsonnenberg** [comment] 2021-12-29 13:42
I have still the same issue as @GetUpdate 
flow state is keeps "disconnected"

**Comment by Bra1nK** [comment] 2021-12-29 13:54
Does this apply https://github.com/hardillb/node-red-alexa-home-skill-web/issues/112#issuecomment-754884628 ?

**Comment by loxatsonnenberg** [comment] 2021-12-29 14:19
> Does this apply [#112 (comment)](https://github.com/hardillb/node-red-alexa-home-skill-web/issues/112#issuecomment-754884628) ?

That I can not confirm.
The flow reports: "Error: Connection refused: Not authorized" in the debug section.
My credidentials are ok, I'm able to select all the devices via NR. They are also discovered with Alexa.

**Comment by hardillb** [comment] 2021-12-29 15:09
OK, the "Not authorized" stuff has nothing to do with this issue (which is clearly about voice command timing out) which is now fixed so I'm closing this issue. We can open a new one to track what's happening with the totally different problem.

**Closed by hardillb** 2021-12-29 15:09 UTC

**Comment by hardillb** [comment] 2021-12-29 15:11
When you open a new issue, include ALL the relevant information. e.g.

-  username
- version of Node-RED
- version of NodeJS
- version of Alexa node
- version of OS
- Anything from the Node-RED console logs (not just the debug sidebar)
- Are you running on Home Assistant (and have you tried to reproduce the problem outside HA)
